# Generated by Django 4.0.1 on 2022-04-30 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppClientes', '0001_initial'),
        ('AppDirecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorDirecciones',
            fields=[
                ('id_proveedorDirecciones', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDirecciones.direcciones')),
            ],
            options={
                'verbose_name': 'Direccion Proveedor',
                'verbose_name_plural': 'Direccion Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('cuit', models.PositiveIntegerField()),
                ('razon_social', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppClientes.condicionfiscal')),
                ('id_proveedorDirecciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProveedores.proveedordirecciones')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
