# Generated by Django 4.0.1 on 2022-06-24 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppDirecciones', '0002_direcciones_id_pais_direcciones_id_provincia'),
        ('AppProveedores', '0002_alter_proveedores_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='id_proveedorDirecciones',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='direccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppDirecciones.direcciones'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProveedorDirecciones',
        ),
    ]
