# Generated by Django 4.0.1 on 2022-04-30 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionFiscal',
            fields=[
                ('id_condicion_fiscal', models.IntegerField(primary_key=True, serialize=False)),
                ('condicion_fiscal', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CondFiscal',
                'verbose_name_plural': 'CondFiscales',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('cuit', models.PositiveIntegerField()),
                ('razon_nombre', models.CharField(max_length=50)),
                ('telefono', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppClientes.condicionfiscal')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
