# Generated by Django 4.0.1 on 2022-06-24 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppDirecciones', '0002_direcciones_id_pais_direcciones_id_provincia'),
        ('AppClientes', '0002_alter_clientes_id_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='direccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppDirecciones.direcciones'),
            preserve_default=False,
        ),
    ]
