# Generated by Django 4.0.1 on 2022-05-07 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppProveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id_tipo_comprobante', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('letra', models.CharField(max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteC',
            fields=[
                ('id_comprobante', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('id_punto_de_venta', models.IntegerField()),
                ('fecha', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProveedores.proveedores')),
                ('id_tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFactura.tipocomprobante')),
            ],
            options={
                'verbose_name': 'ComprobanteC',
                'verbose_name_plural': 'ComprobantesC',
            },
        ),
    ]
