# Generated by Django 4.0.1 on 2022-05-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntosDeVenta',
            fields=[
                ('id_punto_de_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
            ],
            options={
                'verbose_name': 'PuntoDeVenta',
                'verbose_name_plural': 'PuntoDeVentas',
            },
        ),
        migrations.AlterModelOptions(
            name='tipocomprobante',
            options={'verbose_name': 'TipoComprobante', 'verbose_name_plural': 'TipoComprobantes'},
        ),
    ]
