# Generated by Django 4.0.1 on 2022-05-30 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0003_comprobantev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantev',
            name='fecha',
        ),
    ]
