# Generated by Django 4.0.1 on 2022-05-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0006_rename_id_articulo_detallev_id_art_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallev',
            old_name='id_art',
            new_name='articulo',
        ),
    ]
