# Generated by Django 4.0.1 on 2022-05-30 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppClientes', '0001_initial'),
        ('AppFactura', '0007_rename_id_art_detallev_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallev',
            name='id_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppClientes.clientes'),
            preserve_default=False,
        ),
    ]
