# Generated by Django 4.0.1 on 2022-05-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0008_detallev_id_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallev',
            old_name='id_cliente',
            new_name='cliente',
        ),
    ]
