# Generated by Django 4.0.1 on 2022-05-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0009_rename_id_cliente_detallev_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallev',
            options={'verbose_name': 'Detalle', 'verbose_name_plural': 'DetalleVentas'},
        ),
        migrations.AddField(
            model_name='detallev',
            name='bonificacion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
