# Generated by Django 4.0.1 on 2022-05-31 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0010_alter_detallev_options_detallev_bonificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantev',
            name='numero',
        ),
    ]
