# Generated by Django 4.0.1 on 2022-05-31 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0011_remove_comprobantev_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobantev',
            old_name='id_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='comprobantev',
            old_name='id_punto_de_venta',
            new_name='punto_venta',
        ),
        migrations.RenameField(
            model_name='comprobantev',
            old_name='id_tipo_comprobante',
            new_name='tipo_comprobante',
        ),
    ]
