# Generated by Django 4.0.1 on 2022-05-31 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0013_remove_comprobantev_id_comprobante_comprobantev_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallev',
            name='cliente',
        ),
    ]
