# Generated by Django 4.0.1 on 2022-05-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0014_remove_detallev_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantev',
            name='punto_venta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comprobantev',
            name='tipo_comprobante',
            field=models.CharField(max_length=50),
        ),
    ]
