# Generated by Django 4.0.1 on 2022-06-01 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0015_alter_comprobantev_punto_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantev',
            name='id',
        ),
        migrations.RemoveField(
            model_name='comprobantev',
            name='total',
        ),
        migrations.AddField(
            model_name='comprobantev',
            name='id_comprobante',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallev',
            name='id_comprobante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppFactura.comprobantev'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallev',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
