# Generated by Django 4.0.1 on 2022-06-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0016_remove_comprobantev_id_remove_comprobantev_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallev',
            old_name='id_comprobante',
            new_name='comprobante',
        ),
    ]
