# Generated by Django 4.0.1 on 2022-06-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0018_comprobantev_user_detallev_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobantev',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
