# Generated by Django 4.0.1 on 2022-06-01 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppClientes', '0001_initial'),
        ('AppFactura', '0019_comprobantev_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantev',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppClientes.clientes'),
        ),
    ]
