# Generated by Django 4.0.1 on 2022-06-01 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0020_alter_comprobantev_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantev',
            name='punto_venta',
        ),
        migrations.AddField(
            model_name='comprobantev',
            name='punto_venta_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppFactura.puntosdeventa'),
            preserve_default=False,
        ),
    ]
