# Generated by Django 4.0.1 on 2022-06-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0021_remove_comprobantev_punto_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantev',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='comprobantev',
            name='id_comprobante',
        ),
        migrations.RemoveField(
            model_name='comprobantev',
            name='punto_venta_id',
        ),
        migrations.RemoveField(
            model_name='comprobantev',
            name='user',
        ),
        migrations.RemoveField(
            model_name='detallev',
            name='comprobante',
        ),
        migrations.RemoveField(
            model_name='detallev',
            name='total',
        ),
        migrations.RemoveField(
            model_name='detallev',
            name='user',
        ),
        migrations.AddField(
            model_name='comprobantev',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprobantev',
            name='punto_venta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprobantev',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comprobantev',
            name='cliente',
            field=models.IntegerField(),
        ),
    ]
