# Generated by Django 4.0.1 on 2022-06-01 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppFactura', '0022_remove_comprobantev_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobantev',
            options={'ordering': ['id'], 'verbose_name': 'ComprobanteV', 'verbose_name_plural': 'ComprobantesV'},
        ),
        migrations.AlterModelOptions(
            name='detallev',
            options={'ordering': ['id'], 'verbose_name': 'Detalle', 'verbose_name_plural': 'DetalleVentas'},
        ),
        migrations.RenameField(
            model_name='comprobantev',
            old_name='cliente',
            new_name='id_cliente',
        ),
        migrations.RenameField(
            model_name='comprobantev',
            old_name='punto_venta',
            new_name='id_puntoventa',
        ),
        migrations.RenameField(
            model_name='comprobantev',
            old_name='tipo_comprobante',
            new_name='id_tipocomprobante',
        ),
        migrations.RenameField(
            model_name='detallev',
            old_name='bonificacion',
            new_name='id_articulo',
        ),
        migrations.RemoveField(
            model_name='comprobantev',
            name='total',
        ),
        migrations.RemoveField(
            model_name='detallev',
            name='articulo',
        ),
        migrations.AddField(
            model_name='comprobantev',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comprobantev',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallev',
            name='id_comprobante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppFactura.comprobantev'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallev',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallev',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
