# Generated by Django 4.0.1 on 2022-06-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0023_alter_comprobantev_options_alter_detallev_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallev',
            name='bonificacion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
