# Generated by Django 4.0.1 on 2022-06-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0024_detallev_bonificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallev',
            name='porcentaje_iva',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
