# Generated by Django 4.0.1 on 2022-06-21 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppFactura', '0026_alter_comprobantev_id_tipocomprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantec',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='comprobantec',
            name='id_comprobante',
        ),
        migrations.AddField(
            model_name='comprobantec',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprobantec',
            name='monto_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprobantec',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DetalleC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_articulo', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('monto_unitario', models.FloatField()),
                ('porcentaje_iva', models.FloatField()),
                ('bonificacion', models.IntegerField()),
                ('id_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFactura.comprobantec')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'DetalleCompras',
                'ordering': ['id'],
            },
        ),
    ]
