# Generated by Django 4.0.1 on 2022-06-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0027_remove_comprobantec_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantec',
            name='id_tipo_comprobante',
            field=models.IntegerField(),
        ),
    ]
