# Generated by Django 4.0.1 on 2022-06-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0028_alter_comprobantec_id_tipo_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantec',
            name='id_proveedor',
            field=models.IntegerField(),
        ),
    ]
