# Generated by Django 4.0.1 on 2022-06-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0029_alter_comprobantec_id_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantec',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
