# Generated by Django 4.0.1 on 2022-07-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFactura', '0030_alter_comprobantec_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantev',
            name='completed',
        ),
        migrations.AddField(
            model_name='comprobantev',
            name='monto_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
