# Generated by Django 4.0.1 on 2022-08-17 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppFactura', '0032_detallec_subtotal_detallev_subtotal'),
        ('AppProveedores', '0003_remove_proveedores_id_proveedordirecciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFactura.comprobantec')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProveedores.proveedores')),
            ],
            options={
                'verbose_name': 'CCProveedor',
                'verbose_name_plural': 'CCProveedores',
            },
        ),
    ]
